new QC module for improper exposure termination, aka smeared readout
Keck-DataReductionPipelines/KPF-Pipeline pull request #950
Opened 2024-10-23 21:46 UTC by howardisaacson

Exposures that have the smeared readout contribute to noise in the LFC wavelength solution when they are improperly included in the masters stacks. This easy to identify visually on LFC and etalon frames but challenging on ThAr, and darks for example. 
This pull request adds a QC test that checks if the desired exposure time is near to the actual exposure time. These bad-readout frames all have an 'actual' exposure time of between 6 and 6.6 seconds.

2024-10-31 17:33 UTC, bjfultn requested changes

2024-10-31 17:33 UTC, bjfultn commented on modules/quality_control/src/quality_control.py
You also need to add information about this test to the QCDefinitions class.

2024-10-31 19:22 UTC, howardisaacson commented
I added a QC definition. Let me know if you think I should extend it to all levels (L1/L2) or if the L0 qc test will propagate to the next levels.

2024-10-31 19:47 UTC, awhoward commented
I think the L0 check is sufficient as QC keywords are inherited by downstream data products.

2024-10-31 20:25 UTC, howardisaacson commented
QC definitions added on line 574. Please double check. 
A logic error and logic error was also fixed.

2024-11-01 17:45 UTC, bjfultn approved these changes

2024-11-01 17:45 UTC, merged